-- Database: ejercicio1

-- DROP DATABASE ejercicio1;

DROP TABLE IF EXISTS  EMPLEADO CASCADE;
DROP TABLE IF EXISTS  DEPARTAMENTO CASCADE;

CREATE TABLE EMPLEADO(
	ID_empleado SERIAL,
	Apellido VARCHAR(100) NOT NULL,
	ID_depto VARCHAR(30) NOT NULL,

	PRIMARY KEY(ID_empleado)
);

CREATE TABLE DEPARTAMENTO(
	nombre_depto VARCHAR(100) NOT NULL,
	ID_depto VARCHAR(30) NOT NULL,

	PRIMARY KEY(ID_depto)
);


